@extends('layouts.app')
@section('title', __('helal.home'))
@section('content')
    @include('welcome.cover')
    @include('welcome.statistic')
    @include('welcome.doing')
    @include('welcome.news')
    @include('welcome.stories')
    @include('welcome.campaign')
    @include('welcome.martyers')
    @include('welcome.map')    
@endsection
